import { resolveColor } from './useColorStore'
import type { ThemeSlide } from './useColorStore'

const STORAGE_KEY = 'theme-gen-v2'

interface StoredData {
  themes: ThemeSlide[]
  activeId: string
}

export const useThemeStorage = () => {
  function loadData(): StoredData | null {
    if (!import.meta.client) return null
    try {
      const raw = localStorage.getItem(STORAGE_KEY)
      if (!raw) return null
      return JSON.parse(raw) as StoredData
    } catch {
      return null
    }
  }

  function saveData(themes: ThemeSlide[], activeId: string): void {
    localStorage.setItem(STORAGE_KEY, JSON.stringify({ themes, activeId }))
  }

  // Download the raw theme slide as a JSON file — can be re-imported
  function downloadJSON(theme: ThemeSlide): void {
    const payload = JSON.stringify(theme, null, 2)
    triggerDownload(payload, `${slug(theme.name)}.json`, 'application/json')
  }

  // Download a ready-to-use CSS custom properties file
  function downloadCSS(theme: ThemeSlide): void {
    const p = theme.primary.color
    const s = theme.secondary.color
    const lines: string[] = [
      `/* ${theme.name} — generated by Theme Generator */`,
      `/* https://oklch.com for color reference */`,
      ``,
      `:root {`,
      `  --primary:   ${css(p)};`,
      `  --secondary: ${css(s)};`,
    ]

    if (theme.customColors.length) {
      lines.push(``)
      for (const c of theme.customColors) {
        const r = resolveColor(c.delta, p)
        const varName = '--' + c.name.toLowerCase().replace(/\s+/g, '-')
        lines.push(`  ${varName.padEnd(20)} ${css(r)};`)
      }
    }

    if (theme.secondaryColors?.length) {
      lines.push(``)
      for (const c of theme.secondaryColors) {
        const r = resolveColor(c.delta, s)
        const varName = '--' + c.name.toLowerCase().replace(/\s+/g, '-')
        lines.push(`  ${varName.padEnd(20)} ${css(r)};`)
      }
    }

    lines.push(`}`)
    triggerDownload(lines.join('\n'), `${slug(theme.name)}.css`, 'text/css')
  }

  // Parse an uploaded .json file — handles both new ThemeSlide and legacy ThemeData formats
  function parseImport(file: File): Promise<ThemeSlide> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader()
      reader.onload = (e) => {
        try {
          const raw = JSON.parse(e.target!.result as string)
          if (!raw.primary || !raw.secondary) throw new Error('Unrecognised file format')

          resolve({
            id: Date.now().toString(36) + Math.random().toString(36).slice(2),
            name:               raw.name              ?? 'Imported',
            primary:            raw.primary,
            secondary:          raw.secondary,
            customColors:       raw.customColors       ?? [],
            hiddenColorIds:     raw.hiddenColorIds     ?? [],
            secondaryColors:    raw.secondaryColors    ?? [],
            secondaryHiddenIds: raw.secondaryHiddenIds ?? [],
          })
        } catch (err: any) {
          reject(new Error(err.message ?? 'Failed to parse file'))
        }
      }
      reader.onerror = () => reject(new Error('Could not read file'))
      reader.readAsText(file)
    })
  }

  return { loadData, saveData, downloadJSON, downloadCSS, parseImport }
}

// ── helpers ───────────────────────────────────────────────────────────────────

function slug(name: string) {
  return name.trim().replace(/\s+/g, '-').toLowerCase()
}

function css(c: { l: number; c: number; h: number }) {
  return `oklch(${c.l.toFixed(3)} ${c.c.toFixed(3)} ${c.h.toFixed(1)})`
}

function triggerDownload(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
